from enum import Enum

class ExceptionArgument(Enum):
	OBJ = 0
	DICTIONARY = 1
	DICTIONARYCREATIONTHRESHOLD = 2
	ARRAY = 3
	INFO = 4
	KEY = 5
	COLLECTION = 6
	LIST = 7
	MATCH = 8
	CONVERTER = 9
	QUEUE = 10
	STACK = 11
	CAPACITY = 12
	INDEX = 13
	STARTINDEX = 14
	VALUE = 15
	COUNT = 16
	ARRAYINDEX = 17
	NAME = 18
	MODE = 19
	ITEM = 20
	OPTIONS = 21
	VIEW = 22
	SOURCEBYTESTOCOPY = 23

class ExceptionResource(Enum):
	ARGUMENT_IMPLEMENTICOMPARABLE = 0
	ARGUMENT_INVALIDTYPE = 1
	ARGUMENT_INVALIDARGUMENTFORCOMPARISON = 2
	ARGUMENT_INVALIDREGISTRYKEYPERMISSIONCHECK = 3
	ARGUMENTOUTOFRANGE_NEEDNONNEGNUM = 4
	ARG_ARRAYPLUSOFFTOOSMALL = 5
	ARG_NONZEROLOWERBOUND = 6
	ARG_RANKMULTIDIMNOTSUPPORTED = 7
	ARG_REGKEYDELHIVE = 8
	ARG_REGKEYSTRLENBUG = 9
	ARG_REGSETSTRARRNULL = 10
	ARG_REGSETMISMATCHEDKIND = 11
	ARG_REGSUBKEYABSENT = 12
	ARG_REGSUBKEYVALUEABSENT = 13
	ARGUMENT_ADDINGDUPLICATE = 14
	SERIALIZATION_INVALIDONDESER = 15
	SERIALIZATION_MISSINGKEYS = 16
	SERIALIZATION_NULLKEY = 17
	ARGUMENT_INVALIDARRAYTYPE = 18
	NOTSUPPORTED_KEYCOLLECTIONSET = 19
	NOTSUPPORTED_VALUECOLLECTIONSET = 20
	ARGUMENTOUTOFRANGE_SMALLCAPACITY = 21
	ARGUMENTOUTOFRANGE_INDEX = 22
	ARGUMENT_INVALIDOFFLEN = 23
	ARGUMENT_ITEMNOTEXIST = 24
	ARGUMENTOUTOFRANGE_COUNT = 25
	ARGUMENTOUTOFRANGE_INVALIDTHRESHOLD = 26
	ARGUMENTOUTOFRANGE_LISTINSERT = 27
	NOTSUPPORTED_READONLYCOLLECTION = 28
	INVALIDOPERATION_CANNOTREMOVEFROMSTACKORQUEUE = 29
	INVALIDOPERATION_EMPTYQUEUE = 30
	INVALIDOPERATION_ENUMOPCANTHAPPEN = 31
	INVALIDOPERATION_ENUMFAILEDVERSION = 32
	INVALIDOPERATION_EMPTYSTACK = 33
	ARGUMENTOUTOFRANGE_BIGGERTHANCOLLECTION = 34
	INVALIDOPERATION_ENUMNOTSTARTED = 35
	INVALIDOPERATION_ENUMENDED = 36
	NOTSUPPORTED_SORTEDLISTNESTEDWRITE = 37
	INVALIDOPERATION_NOVALUE = 38
	INVALIDOPERATION_REGREMOVESUBKEY = 39
	SECURITY_REGISTRYPERMISSION = 40
	UNAUTHORIZEDACCESS_REGISTRYNOWRITE = 41
	OBJECTDISPOSED_REGKEYCLOSED = 42
	NOTSUPPORTED_INCOMPARABLETYPE = 43
	ARGUMENT_INVALIDREGISTRYOPTIONSCHECK = 44
	ARGUMENT_INVALIDREGISTRYVIEWCHECK = 45

class StringSplitOptions(Enum):
	NONE = 0
	REMOVEEMPTYENTRIES = 1

class StringComparison(Enum):
	CURRENTCULTURE = 0
	CURRENTCULTUREIGNORECASE = 1
	INVARIANTCULTURE = 2
	INVARIANTCULTUREIGNORECASE = 3
	ORDINAL = 4
	ORDINALIGNORECASE = 5

class DateTimeKind(Enum):
	UNSPECIFIED = 0
	UTC = 1
	LOCAL = 2

class DelegateBindingFlags(Enum):
	STATICMETHODONLY = 1
	INSTANCEMETHODONLY = 2
	OPENDELEGATEONLY = 4
	CLOSEDDELEGATEONLY = 8
	NEVERCLOSEOVERNULL = 16
	CASELESSMATCHING = 32
	SKIPSECURITYCHECKS = 64
	RELAXEDSIGNATURE = 128

class LogLevel(Enum):
	TRACE = 0
	STATUS = 20
	WARNING = 40
	ERROR = 50
	PANIC = 100

class AppDomainManagerInitializationOptions(Enum):
	NONE = 0
	REGISTERWITHHOST = 1

class LoaderOptimization(Enum):
	NOTSPECIFIED = 0
	SINGLEDOMAIN = 1
	MULTIDOMAIN = 2
	MULTIDOMAINHOST = 3
	DOMAINMASK = 3
	DISALLOWBINDINGS = 4

class AttributeTargets(Enum):
	ASSEMBLY = 1
	MODULE = 2
	CLASS = 4
	STRUCT = 8
	ENUM = 16
	CONSTRUCTOR = 32
	METHOD = 64
	PROPERTY = 128
	FIELD = 256
	EVENT = 512
	INTERFACE = 1024
	PARAMETER = 2048
	DELEGATE = 4096
	RETURNVALUE = 8192
	GENERICPARAMETER = 16384
	ALL = 32767

class ConfigEvents(Enum):
	STARTDOCUMENT = 0
	STARTDTD = 1
	ENDDTD = 2
	STARTDTDSUBSET = 3
	ENDDTDSUBSET = 4
	ENDPROLOG = 5
	STARTENTITY = 6
	ENDENTITY = 7
	ENDDOCUMENT = 8
	DATAAVAILABLE = 9
	LASTEVENT = 9

class ConfigNodeType(Enum):
	ELEMENT = 1
	ATTRIBUTE = 2
	PI = 3
	XMLDECL = 4
	DOCTYPE = 5
	DTDATTRIBUTE = 6
	ENTITYDECL = 7
	ELEMENTDECL = 8
	ATTLISTDECL = 9
	NOTATION = 10
	GROUP = 11
	INCLUDESECT = 12
	PCDATA = 13
	CDATA = 14
	IGNORESECT = 15
	COMMENT = 16
	ENTITYREF = 17
	WHITESPACE = 18
	NAME = 19
	NMTOKEN = 20
	STRING = 21
	PEREF = 22
	MODEL = 23
	ATTDEF = 24
	ATTTYPE = 25
	ATTPRESENCE = 26
	DTDSUBSET = 27
	LASTNODETYPE = 28

class ConfigNodeSubType(Enum):
	VERSION = 28
	ENCODING = 29
	STANDALONE = 30
	NS = 31
	XMLSPACE = 32
	XMLLANG = 33
	SYSTEM = 34
	PUBLIC = 35
	NDATA = 36
	ATCDATA = 37
	ATID = 38
	ATIDREF = 39
	ATIDREFS = 40
	ATENTITY = 41
	ATENTITIES = 42
	ATNMTOKEN = 43
	ATNMTOKENS = 44
	ATNOTATION = 45
	ATREQUIRED = 46
	ATIMPLIED = 47
	ATFIXED = 48
	PENTITYDECL = 49
	EMPTY = 50
	ANY = 51
	MIXED = 52
	SEQUENCE = 53
	CHOICE = 54
	STAR = 55
	PLUS = 56
	QUESTIONMARK = 57
	LASTSUBNODETYPE = 58

class ConsoleColor(Enum):
	BLACK = 0
	DARKBLUE = 1
	DARKGREEN = 2
	DARKCYAN = 3
	DARKRED = 4
	DARKMAGENTA = 5
	DARKYELLOW = 6
	GRAY = 7
	DARKGRAY = 8
	BLUE = 9
	GREEN = 10
	CYAN = 11
	RED = 12
	MAGENTA = 13
	YELLOW = 14
	WHITE = 15

class ConsoleKey(Enum):
	BACKSPACE = 8
	TAB = 9
	CLEAR = 12
	ENTER = 13
	PAUSE = 19
	ESCAPE = 27
	SPACEBAR = 32
	PAGEUP = 33
	PAGEDOWN = 34
	END = 35
	HOME = 36
	LEFTARROW = 37
	UPARROW = 38
	RIGHTARROW = 39
	DOWNARROW = 40
	SELECT = 41
	PRINT = 42
	EXECUTE = 43
	PRINTSCREEN = 44
	INSERT = 45
	DELETE = 46
	HELP = 47
	D0 = 48
	D1 = 49
	D2 = 50
	D3 = 51
	D4 = 52
	D5 = 53
	D6 = 54
	D7 = 55
	D8 = 56
	D9 = 57
	A = 65
	B = 66
	C = 67
	D = 68
	E = 69
	F = 70
	G = 71
	H = 72
	I = 73
	J = 74
	K = 75
	L = 76
	M = 77
	N = 78
	O = 79
	P = 80
	Q = 81
	R = 82
	S = 83
	T = 84
	U = 85
	V = 86
	W = 87
	X = 88
	Y = 89
	Z = 90
	LEFTWINDOWS = 91
	RIGHTWINDOWS = 92
	APPLICATIONS = 93
	SLEEP = 95
	NUMPAD0 = 96
	NUMPAD1 = 97
	NUMPAD2 = 98
	NUMPAD3 = 99
	NUMPAD4 = 100
	NUMPAD5 = 101
	NUMPAD6 = 102
	NUMPAD7 = 103
	NUMPAD8 = 104
	NUMPAD9 = 105
	MULTIPLY = 106
	ADD = 107
	SEPARATOR = 108
	SUBTRACT = 109
	DECIMAL = 110
	DIVIDE = 111
	F1 = 112
	F2 = 113
	F3 = 114
	F4 = 115
	F5 = 116
	F6 = 117
	F7 = 118
	F8 = 119
	F9 = 120
	F10 = 121
	F11 = 122
	F12 = 123
	F13 = 124
	F14 = 125
	F15 = 126
	F16 = 127
	F17 = 128
	F18 = 129
	F19 = 130
	F20 = 131
	F21 = 132
	F22 = 133
	F23 = 134
	F24 = 135
	BROWSERBACK = 166
	BROWSERFORWARD = 167
	BROWSERREFRESH = 168
	BROWSERSTOP = 169
	BROWSERSEARCH = 170
	BROWSERFAVORITES = 171
	BROWSERHOME = 172
	VOLUMEMUTE = 173
	VOLUMEDOWN = 174
	VOLUMEUP = 175
	MEDIANEXT = 176
	MEDIAPREVIOUS = 177
	MEDIASTOP = 178
	MEDIAPLAY = 179
	LAUNCHMAIL = 180
	LAUNCHMEDIASELECT = 181
	LAUNCHAPP1 = 182
	LAUNCHAPP2 = 183
	OEM1 = 186
	OEMPLUS = 187
	OEMCOMMA = 188
	OEMMINUS = 189
	OEMPERIOD = 190
	OEM2 = 191
	OEM3 = 192
	OEM4 = 219
	OEM5 = 220
	OEM6 = 221
	OEM7 = 222
	OEM8 = 223
	OEM102 = 226
	PROCESS = 229
	PACKET = 231
	ATTENTION = 246
	CRSEL = 247
	EXSEL = 248
	ERASEENDOFFILE = 249
	PLAY = 250
	ZOOM = 251
	NONAME = 252
	PA1 = 253
	OEMCLEAR = 254

class ConsoleModifiers(Enum):
	ALT = 1
	SHIFT = 2
	CONTROL = 4

class ConsoleSpecialKey(Enum):
	CONTROLC = 0
	CONTROLBREAK = 1

class Base64FormattingOptions(Enum):
	NONE = 0
	INSERTLINEBREAKS = 1

class DayOfWeek(Enum):
	SUNDAY = 0
	MONDAY = 1
	TUESDAY = 2
	WEDNESDAY = 3
	THURSDAY = 4
	FRIDAY = 5
	SATURDAY = 6

class EnvironmentVariableTarget(Enum):
	PROCESS = 0
	USER = 1
	MACHINE = 2

class GCCollectionMode(Enum):
	DEFAULT = 0
	FORCED = 1
	OPTIMIZED = 2

class InternalGCCollectionMode(Enum):
	NONBLOCKING = 1
	BLOCKING = 2
	OPTIMIZED = 4
	COMPACTING = 8

class GCNotificationStatus(Enum):
	SUCCEEDED = 0
	FAILED = 1
	CANCELED = 2
	TIMEOUT = 3
	NOTAPPLICABLE = 4

class MidpointRounding(Enum):
	TOEVEN = 0
	AWAYFROMZERO = 1

class PlatformID(Enum):
	WIN32S = 0
	WIN32WINDOWS = 1
	WIN32NT = 2
	WINCE = 3
	UNIX = 4
	XBOX = 5
	MACOSX = 6

class TypeNameFormatFlags(Enum):
	FORMATBASIC = 0
	FORMATNAMESPACE = 1
	FORMATFULLINST = 2
	FORMATASSEMBLY = 4
	FORMATSIGNATURE = 8
	FORMATNOVERSION = 16
	FORMATANGLEBRACKETS = 64
	FORMATSTUBINFO = 128
	FORMATGENERICPARAM = 256
	FORMATSERIALIZATION = 259

class TypeNameKind(Enum):
	NAME = 0
	TOSTRING = 1
	SERIALIZATIONNAME = 2
	FULLNAME = 3

class TimeZoneInfoOptions(Enum):
	NONE = 1
	NOTHROWONINVALIDTIME = 2

class TypeCode(Enum):
	EMPTY = 0
	OBJECT = 1
	DBNULL = 2
	BOOLEAN = 3
	CHAR = 4
	SBYTE = 5
	BYTE = 6
	INT16 = 7
	UINT16 = 8
	INT32 = 9
	UINT32 = 10
	INT64 = 11
	UINT64 = 12
	SINGLE = 13
	DOUBLE = 14
	DECIMAL = 15
	DATETIME = 16
	STRING = 18

class DTSubStringType(Enum):
	UNKNOWN = 0
	INVALID = 1
	NUMBER = 2
	END = 3
	OTHER = 4

class ParseFailureKind(Enum):
	NONE = 0
	ARGUMENTNULL = 1
	FORMAT = 2
	FORMATWITHPARAMETER = 3
	FORMATBADDATETIMECALENDAR = 4

class ParseFlags(Enum):
	HAVEYEAR = 1
	HAVEMONTH = 2
	HAVEDAY = 4
	HAVEHOUR = 8
	HAVEMINUTE = 16
	HAVESECOND = 32
	HAVETIME = 64
	HAVEDATE = 128
	TIMEZONEUSED = 256
	TIMEZONEUTC = 512
	PARSEDMONTHNAME = 1024
	CAPTUREOFFSET = 2048
	YEARDEFAULT = 4096
	RFC1123PATTERN = 8192
	UTCSORTPATTERN = 16384

class TokenType(Enum):
	NUMBERTOKEN = 1
	YEARNUMBERTOKEN = 2
	AM = 3
	PM = 4
	MONTHTOKEN = 5
	ENDOFSTRING = 6
	DAYOFWEEKTOKEN = 7
	TIMEZONETOKEN = 8
	ERATOKEN = 9
	DATEWORDTOKEN = 10
	UNKNOWNTOKEN = 11
	HEBREWNUMBER = 12
	JAPANESEERATOKEN = 13
	TERATOKEN = 14
	IGNORABLESYMBOL = 15
	REGULARTOKENMASK = 255
	SEP_UNK = 256
	SEP_END = 512
	SEP_SPACE = 768
	SEP_AM = 1024
	SEP_PM = 1280
	SEP_DATE = 1536
	SEP_TIME = 1792
	SEP_YEARSUFF = 2048
	SEP_MONTHSUFF = 2304
	SEP_DAYSUFF = 2560
	SEP_HOURSUFF = 2816
	SEP_MINUTESUFF = 3072
	SEP_SECONDSUFF = 3328
	SEP_LOCALTIMEMARK = 3584
	SEP_DATEOROFFSET = 3840
	SEPARATORTOKENMASK = 65280

class CompatibilityFlag(Enum):
	SWALLOWUNHANDLEDEXCEPTIONS = 0
	NULLREFERENCEEXCEPTIONONAV = 1
	EAGERLYGENERATERANDOMASYMMKEYS = 2
	FULLTRUSTLISTASSEMBLIESINGAC = 3
	DATETIMEPARSEIGNOREPUNCTUATION = 4
	ONLYGACDOMAINNEUTRAL = 5
	DISABLEREPLACEMENTCUSTOMCULTURE = 6

class SwitchValueState(Enum):
	HASFALSEVALUE = 1
	HASTRUEVALUE = 2
	HASLOOKEDFOROVERRIDE = 4
	UNKNOWNVALUE = 8

class ExceptionMessageKind(Enum):
	THREADABORT = 1
	THREADINTERRUPTED = 2
	OUTOFMEMORY = 3

class APPX_FLAGS(Enum):
	APPX_FLAGS_INITIALIZED = 1
	APPX_FLAGS_APPX_MODEL = 2
	APPX_FLAGS_APPX_DESIGN_MODE = 4
	APPX_FLAGS_APPX_NGEN = 8
	APPX_FLAGS_APPX_MASK = 14
	APPX_FLAGS_API_CHECK = 16

class LoaderInformation(Enum):
	APPLICATIONBASEVALUE = 0
	CONFIGURATIONFILEVALUE = 1
	DYNAMICBASEVALUE = 2
	DEVPATHVALUE = 3
	APPLICATIONNAMEVALUE = 4
	PRIVATEBINPATHVALUE = 5
	PRIVATEBINPATHPROBEVALUE = 6
	SHADOWCOPYDIRECTORIESVALUE = 7
	SHADOWCOPYFILESVALUE = 8
	CACHEPATHVALUE = 9
	LICENSEFILEVALUE = 10
	DISALLOWPUBLISHERPOLICYVALUE = 11
	DISALLOWCODEDOWNLOADVALUE = 12
	DISALLOWBINDINGREDIRECTSVALUE = 13
	DISALLOWAPPBASEPROBINGVALUE = 14
	CONFIGURATIONBYTESVALUE = 15
	LOADERMAXIMUM = 18

class ContextForm(Enum):
	LOOSE = 0
	STOREBOUNDED = 1

class ApplicationState(Enum):
	UNDEFINED = 0
	STARTING = 1
	RUNNING = 2

class ApplicationStateDisposition(Enum):
	UNDEFINED = 0
	STARTING = 1
	RUNNING = 2
	STARTINGMIGRATED = 65537
	RUNNINGFIRSTTIME = 131074

class ControlKeyState(Enum):
	RIGHTALTPRESSED = 1
	LEFTALTPRESSED = 2
	RIGHTCTRLPRESSED = 4
	LEFTCTRLPRESSED = 8
	SHIFTPRESSED = 16
	NUMLOCKON = 32
	SCROLLLOCKON = 64
	CAPSLOCKON = 128
	ENHANCEDKEY = 256

class ParseFailureKind(Enum):
	NONE = 0
	ARGUMENT = 1
	ARGUMENTNULL = 2
	ARGUMENTWITHPARAMETER = 3
	UNHANDLEDEXCEPTION = 4

class SpecialFolderOption(Enum):
	NONE = 0
	DONOTVERIFY = 16384
	CREATE = 32768

class SpecialFolder(Enum):
	DESKTOP = 0
	PROGRAMS = 2
	MYDOCUMENTS = 5
	PERSONAL = 5
	FAVORITES = 6
	STARTUP = 7
	RECENT = 8
	SENDTO = 9
	STARTMENU = 11
	MYMUSIC = 13
	MYVIDEOS = 14
	DESKTOPDIRECTORY = 16
	MYCOMPUTER = 17
	NETWORKSHORTCUTS = 19
	FONTS = 20
	TEMPLATES = 21
	COMMONSTARTMENU = 22
	COMMONPROGRAMS = 23
	COMMONSTARTUP = 24
	COMMONDESKTOPDIRECTORY = 25
	APPLICATIONDATA = 26
	PRINTERSHORTCUTS = 27
	LOCALAPPLICATIONDATA = 28
	INTERNETCACHE = 32
	COOKIES = 33
	HISTORY = 34
	COMMONAPPLICATIONDATA = 35
	WINDOWS = 36
	SYSTEM = 37
	PROGRAMFILES = 38
	MYPICTURES = 39
	USERPROFILE = 40
	SYSTEMX86 = 41
	PROGRAMFILESX86 = 42
	COMMONPROGRAMFILES = 43
	COMMONPROGRAMFILESX86 = 44
	COMMONTEMPLATES = 45
	COMMONDOCUMENTS = 46
	COMMONADMINTOOLS = 47
	ADMINTOOLS = 48
	COMMONMUSIC = 53
	COMMONPICTURES = 54
	COMMONVIDEOS = 55
	RESOURCES = 56
	LOCALIZEDRESOURCES = 57
	COMMONOEMLINKS = 58
	CDBURNING = 59

class StartNoGCRegionStatus(Enum):
	SUCCEEDED = 0
	NOTENOUGHMEMORY = 1
	AMOUNTTOOLARGE = 2
	ALREADYINPROGRESS = 3

class EndNoGCRegionStatus(Enum):
	SUCCEEDED = 0
	NOTINPROGRESS = 1
	GCINDUCED = 2
	ALLOCATIONEXCEEDED = 3

class GuidStyles(Enum):
	NUMBERFORMAT = 0
	NONE = 0
	ALLOWPARENTHESIS = 1
	ALLOWBRACES = 2
	ALLOWDASHES = 4
	ALLOWHEXPREFIX = 8
	ANY = 15
	REQUIREPARENTHESIS = 16
	REQUIREBRACES = 32
	REQUIREDASHES = 64
	DIGITFORMAT = 64
	PARENTHESISFORMAT = 80
	BRACEFORMAT = 96
	REQUIREHEXPREFIX = 128
	HEXFORMAT = 160

class GuidParseThrowStyle(Enum):
	NONE = 0
	ALL = 1
	ALLBUTOVERFLOW = 2

class ParseFailureKind(Enum):
	NONE = 0
	ARGUMENTNULL = 1
	FORMAT = 2
	FORMATWITHPARAMETER = 3
	NATIVEEXCEPTION = 4
	FORMATWITHINNEREXCEPTION = 5

class MemberListType(Enum):
	ALL = 0
	CASESENSITIVE = 1
	CASEINSENSITIVE = 2
	HANDLETOINFO = 3

class DispatchWrapperType(Enum):
	UNKNOWN = 1
	DISPATCH = 2
	RECORD = 4
	ERROR = 8
	CURRENCY = 16
	BSTR = 32
	SAFEARRAY = 65536

class MdSigCallingConvention(Enum):
	DEFAULT = 0
	C = 1
	STDCALL = 2
	THISCALL = 3
	FASTCALL = 4
	VARARG = 5
	FIELD = 6
	LOCALSIG = 7
	PROPERTY = 8
	UNMGD = 9
	GENERICINST = 10
	MAX = 11
	CALLCONVMASK = 15
	GENERICS = 16
	HASTHIS = 32
	EXPLICITTHIS = 64

class TimeZoneInfoResult(Enum):
	SUCCESS = 0
	TIMEZONENOTFOUNDEXCEPTION = 1
	INVALIDTIMEZONEEXCEPTION = 2
	SECURITYEXCEPTION = 3

class ParseFailureKind(Enum):
	ARGUMENTNULLEXCEPTION = 0
	ARGUMENTEXCEPTION = 1
	ARGUMENTOUTOFRANGEEXCEPTION = 2
	FORMATEXCEPTION = 3

class DTT(Enum):
	END = 0
	NUMEND = 1
	NUMAMPM = 2
	NUMSPACE = 3
	NUMDATESEP = 4
	NUMTIMESEP = 5
	MONTHEND = 6
	MONTHSPACE = 7
	MONTHDATESEP = 8
	NUMDATESUFF = 9
	NUMTIMESUFF = 10
	DAYOFWEEK = 11
	YEARSPACE = 12
	YEARDATESEP = 13
	YEAREND = 14
	TIMEZONE = 15
	ERA = 16
	NUMUTCTIMEMARK = 17
	UNK = 18
	NUMLOCALTIMEMARK = 19
	MAX = 20

class TM(Enum):
	AM = 0
	PM = 1
	NOTSET = -1

class DS(Enum):
	BEGIN = 0
	N = 1
	NN = 2
	D_ND = 3
	D_NN = 4
	D_NND = 5
	D_M = 6
	D_MN = 7
	D_NM = 8
	D_MND = 9
	D_NDS = 10
	D_Y = 11
	D_YN = 12
	D_YND = 13
	D_YM = 14
	D_YMD = 15
	D_S = 16
	T_S = 17
	T_NT = 18
	T_NNT = 19
	ERROR = 20
	DX_NN = 21
	DX_NNN = 22
	DX_MN = 23
	DX_NM = 24
	DX_MNN = 25
	DX_DS = 26
	DX_DSN = 27
	DX_NDS = 28
	DX_NNDS = 29
	DX_YNN = 30
	DX_YMN = 31
	DX_YN = 32
	DX_YM = 33
	TX_N = 34
	TX_NN = 35
	TX_NNN = 36
	TX_TS = 37
	DX_NNY = 38

class CacheType(Enum):
	METHOD = 0
	CONSTRUCTOR = 1
	FIELD = 2
	PROPERTY = 3
	EVENT = 4
	INTERFACE = 5
	NESTEDTYPE = 6

class State(Enum):
	ESCAPED = 0
	NOTESCAPED = 1
	STARTOFTOKEN = 2
	ENDOFLINE = 3

class ICloneable:

	def __init__(self) -> None:
		"""Creating a new Instance of this class is not allowed


		Raises
		--------
			Exception: if this class is instantiated
		"""
		raise Exception("Creating a new Instance of this class is not allowed")
		pass

	def Clone(self) -> object:
		"""No Description

		Returns
		--------
			``object`` : 
		"""
		pass

class EventArgs:

	def __init__(self) -> None:
		"""No Description
		"""
		pass

