from enum import Enum
from System import TypeCode

class IdahoAlternativeTypes(Enum):
	HMIDATASETGEOMETRYALTERNATIVE = 1
	HMIDATASETTOPOLOGYALTERNATIVE = 2
	HMIACTIVETOPOLOGYALTERNATIVE = 3
	PHYSICALALTERNATIVE = 4
	DEMANDALTERNATIVE = 20
	INITIALSETTINGSALTERNATIVE = 21
	OPERATIONALALTERNATIVE = 22
	AGEALTERNATIVE = 23
	CONSTITUENTALTERNATIVE = 24
	TRACEALTERNATIVE = 25
	FIREFLOWALTERNATIVE = 26
	CAPITALCOSTALTERNATIVE = 27
	ENERGYCOSTALTERNATIVE = 28
	PRESSUREDEPENDENTDEMANDALTERNATIVE = 29
	CRITICALITYALTERNATIVE = 30
	HMIUSERDEFINEDEXTENSIONSALTERNATIVE = 100

class DemandTypeEnum(Enum):
	DEMANDTYPE = 0
	INFLOWTYPE = 1

class SCADAUnitDemandSourceType(Enum):
	USERDEFINEDTYPE = 0
	SIGNALTYPE = 1

class SCADANormalDemandSourceType(Enum):
	USERDEFINEDTYPE = 0
	SIGNALTYPE = 1

class TankSectionEnum(Enum):
	CIRCULARTANKSECTIONTYPE = 0
	NONCIRCULARTANKSECTIONTYPE = 1
	VARIABLEAREATANKSECTIONTYPE = 2

class OperatingRangeTypeEnum(Enum):
	OPERATINGRANGE_ELEVATIONTYPE = 0
	OPERATINGRANGE_LEVELTYPE = 1

class TankMixingModelEnum(Enum):
	TWOCOMPARTMENTTYPE = 0
	COMPLETELYMIXEDTYPE = 1
	FIFOTYPE = 2
	LIFOTYPE = 3

class ConstituentSourceTypeEnum(Enum):
	CONCENTRATIONTYPE = 0
	FLOWPACEDBOOSTERTYPE = 1
	SETPOINTBOOSTERTYPE = 2
	MASSBOOSTERTYPE = 3

class ValveSettingEnum(Enum):
	VALVEACTIVETYPE = 0
	VALVEINACTIVETYPE = 1
	VALVECLOSEDTYPE = 2

class PressureValveSettingEnum(Enum):
	VALVEPRESSURETYPE = 0
	VALVEHGLTYPE = 1

class PumpStatusEnum(Enum):
	PUMPONTYPE = 0
	PUMPOFFTYPE = 1
	PUMPRESULTCANNOTDELIVERHEAD = 2
	PUMPRESULTCANNOTDELIVERFLOW = 3

class PumpResultControlStatus(Enum):
	PUMPRESULTONTYPE = 0
	PUMPRESULTOFFTYPE = 1
	PUMPRESULTCANNOTDELIVERHEADTYPE = 2
	PUMPRESULTCANNOTDELIVERFLOWTYPE = 3

class VSPTypeEnum(Enum):
	PATTERNBASEDTYPE = 0
	FIXEDHEADTYPE = 1
	FIXEDFLOWTYPE = 2

class PipeStatusEnum(Enum):
	OPENTYPE = 0
	CLOSEDTYPE = 1

class TurbineStatusEnum(Enum):
	OPENTYPE = 0
	CLOSEDTYPE = 1

class IdahoDomainElementTypes(Enum):
	IDAHOTANKELEMENTMANAGER = 52
	IDAHOHYDRANTELEMENTMANAGER = 54
	IDAHOJUNCTIONELEMENTMANAGER = 55
	IDAHORESERVOIRELEMENTMANAGER = 56
	FCVELEMENTMANAGER = 60
	TCVELEMENTMANAGER = 61
	GPVELEMENTMANAGER = 62
	PRVELEMENTMANAGER = 64
	PSVELEMENTMANAGER = 65
	PBVELEMENTMANAGER = 66
	STANDARDPUMPELEMENTMANAGER = 68
	IDAHOPIPEELEMENTMANAGER = 69
	IDAHOSPOTELEVATIONELEMENTMANAGER = 70
	PRESSUREISOLATIONVALVEELEMENTMANAGER = 71
	VARIABLESPEEDPUMPBATTERYELEMENTMANAGER = 72

class ApplyFireFlowsEnum(Enum):
	ADDTOBASELINETYPE = 0
	REPLACEBASELINETYPE = 1

class NumericalEngineTypeEnum(Enum):
	EPANETENGINE = 1

class EpaNetEngine_TimeAnalysisTypeEnum(Enum):
	STEADYSTATETYPE = 0
	EPSTYPE = 1

class EpaNetEngine_CalculationTypeEnum(Enum):
	FIREFLOWTYPE = 0
	FLUSHINGTYPE = 1
	AGEANALYSISTYPE = 2
	CONSTITUENTANALYSISTYPE = 3
	TRACEANALYSISTYPE = 4
	HYDRAULICSONLYTYPE = 5
	MSXANALYSISTYPE = 6
	SCADAANALAYSISTYPE = 7
	QUALITYANALYSISTYPE = 8
	CRITICALITYTYPE = 9999

class EpaNetEngine_WaterQualityAnalysisEnum(Enum):
	NOANALYSISTYPE = 0
	AGEANALYSISTYPE = 1
	CONSTITUENTANALYSISTYPE = 2
	TRACEANALYSISTYPE = 3
	ALLQUALITIESTYPE = 4

class EpaNetEngine_FrictionMethodEnum(Enum):
	DARCYWEISBACHTYPE = 0
	HAZENWILLIAMSTYPE = 1
	MANNINGSTYPE = 2

class EpaNetEngine_EngineCompatibilityEnum(Enum):
	V8ISS2 = 0
	V8ISS1 = 1
	EPANET2_12 = 2
	EPANET2_10 = 3

class EpaNetEngine_OverrideReportingTimeStepEnum(Enum):
	ALL = 0
	CONSTANT = 1
	VARIABLE = 2

class IsolationValveInitialSettingEnum(Enum):
	ISOLATIONVALVEOPENTYPE = 0
	ISOLATIONVALVECLOSEDTYPE = 1

class SegmentationScopeType(Enum):
	ENTIRENETWORK = 0
	SUBSETNETWORK = 1

class MinorLossTypeEnum(Enum):
	ENTRANCETYPE = 0
	BENDTYPE = 1
	CONTRACTIONTYPE = 2
	CROSSTYPE = 3
	EXITTYPE = 4
	EXPANSIONTYPE = 5
	TEETYPE = 6
	VALVETYPE = 7
	WYETYPE = 8

class TCVCoefficientType(Enum):
	HEADLOSS = 1
	DISCHARGE = 2
	VALVECHARACTERISTICSCURVE = 3

class ControlValveCoefficientType(Enum):
	MINORLOSS = 1
	DISCHARGECOEFFICIENT = 2

class BoundaryPumpStatusEnum(Enum):
	PUMPON = 0
	PUMPOFF = 1

class BoundaryPressureValveStatusEnum(Enum):
	INACTIVE = 0
	CLOSED = 1

class BoundaryPipeStatusEnum(Enum):
	PIPEOPEN = 0
	PIPECLOSED = 1

class BoundaryGPVStatusEnum(Enum):
	ACTIVE = 0
	CLOSED = 1

class BoundaryTCVStatusEnum(Enum):
	CLOSED = 0
	INACTIVE = 1

class BoundaryFCVStatusEnum(Enum):
	CLOSED = 0
	INACTIVE = 1

class BoundaryTankAttributeEnum(Enum):
	TANKHGL = 0
	TANKLEVEL = 1

class BoundaryPumpAttributeEnum(Enum):
	PUMPSETTING = 0
	PUMPSTATUS = 1

class BoundaryPressureValveAttributeEnum(Enum):
	VALVESETTING = 0
	VALVESTATUS = 6

class BoundaryTCVAttributeEnum(Enum):
	VALVESETTING = 0
	VALVESTATUS = 1

class BoundaryFCVAttributeEnum(Enum):
	VALVESETTING = 0
	VALVESTATUS = 1

class TargetNodeAttributeEnum(Enum):
	HGL = 0
	PRESSURE = 1

class TargetDirectedNodeAttributeEnum(Enum):
	FLOW = 0
	HGLIN = 1
	HGLOUT = 2
	PRESSUREIN = 3
	PRESSUREOUT = 4

class ObservedTargetElementTypeEnum(Enum):
	TARGETNODE = 1
	TARGETDIRECTEDNODE = 2
	TARGETPIPE = 7

class BoundaryTargetElementTypeEnum(Enum):
	TANK = 0
	PUMP = 2
	PRESSUREVALVE = 3
	GPV = 4
	PIPE = 5
	TCV = 6
	FCV = 7

class InitialTransientPumpStatusEnum(Enum):
	PUMPON = 0
	PUMPOFF = 1

class RunDurationTypeEnum(Enum):
	TIMESTEPS = 0
	TIMES = 1

class ReportPointHistoryTypeEnum(Enum):
	ALL = 0
	ONLYIFONPATH = 1

class ShowExtremeHeadsAfterEnum(Enum):
	AFTERTIMEZERO = 0
	AFTERFIRSTMAXMIN = 1

class TransientFrictionMethodEnum(Enum):
	STEADY = 0
	QUASISTEADY = 1
	UNSTEADY = 2
	UNSTEADYVITKOVSKY = 3

class TurbineOperatingCaseEnum(Enum):
	INSTANTLOADREJECTION = 0
	LOADREJECTION = 1
	LOADACCEPTANCE = 2
	LOADVARIATION = 3

class AirValveTypeEnum(Enum):
	SLOWCLOSING = 0
	DOUBLEACTING = 1
	TRIPLEACTING = 2
	VACUUMBREAKER = 3

class SAV_SRVTypeEnum(Enum):
	SAV = 0
	SRV = 1
	SAVANDSRV = 2

class SAVValveTypeEnum(Enum):
	NEEDLE = 0
	CIRCULARGATE = 1
	GLOBAL = 2
	BALL = 3
	BUTTERFLY = 4

class SRVControlTypeEnum(Enum):
	SPRINGLOADED = 0
	TIMEBASED = 1

class SRVValveTypeEnum(Enum):
	NEEDLE = 0
	CIRCULARGATE = 1
	GLOBE = 2
	BALL = 3
	BUTTERFLY = 4

class RuptureDiskOrificeDefinitionType(Enum):
	SIMPLE = 0
	ORIFICEEQUATION = 1

class FlowHeadRelationshipEnum(Enum):
	SIMPLE = 0
	BASICEMITTER = 1
	ORIFICEEQUATION = 2

class DischargeToAtmosphereTypeEnum(Enum):
	ORIFICE = 0
	VALVE = 1
	RATINGCURVE = 2

class ValveTypeInitialStatusEnum(Enum):
	OPEN = 1
	CLOSED = 2

class HammerPumpTypeEnum(Enum):
	SHUTDOWN = 0
	CONSTANTSPEEDNOPUMPCURVE = 1
	CONSTANTSPEEDWITHPUMPCURVE = 2
	VSP = 3
	PUMPSTARTVSP = 4

class HammerPumpValveTypeEnum(Enum):
	CHECKVALVE = 0
	CONTROLVALVE = 1

class VariableSpeedType_ControlVariableEnum(Enum):
	SPEED = 0
	TORQUE = 1

class SpecificSpeedEnum(Enum):
	SI25_US1280 = 0
	SI35_US1800 = 1
	SI94_US4850 = 2
	SI117_US6040 = 3
	SI145_US7500 = 4
	SI208_US10740 = 5
	SI260_US13500 = 6

class CheckValveFlowDirectionEnum(Enum):
	TOWARDSWYE = 0
	AWAYFROMWYE = 1

class CheckValveClosureTypeEnum(Enum):
	INSTANTANEOUSCLOSURE = 0
	SLOWCLOSURE = 1
	DYNAMICCHARACTERISTICSCURVE = 2

class SurgeTankTypeEnum(Enum):
	SIMPLE = 0
	DIFFERENTIAL = 1

class TypeOfVolumeEnum(Enum):
	AIR = 0
	VAPOR = 1

class HammerValveType(Enum):
	BUTTERFLY = 0
	NEEDLE = 1
	CIRCULARGATE = 2
	GLOBE = 3
	BALL = 4
	USERDEFINED = 5

class TimestepAdjustmentAttribute(Enum):
	LENGTH = 0
	WAVESPEED = 1

class TimestepAdjustmentType(Enum):
	RELATIVE = 0
	ABSOLUTE = 1

class GPVTransientBehaviorEnum(Enum):
	ORIFICE = 0
	VALVE = 1

class PeriodicHeadFlowBehaviorEnum(Enum):
	HEAD = 0
	FLOW = 1

class HammerReportPointsEnum(Enum):
	NOPOINTS = 0
	ALLPOINTS = 1
	SELECTEDPOINTS = 2

class HammerReportTimesEnum(Enum):
	PERIODICALLY = 0
	ATNOTIMES = 1
	ATALLTIMES = 2
	ATSPECIFICTIMES = 3

class HammerLevelOfPrecision(Enum):
	LOWEST = 0
	LOW = 1
	MEDIUM = 2
	HIGH = 3
	HIGHEST = 4

class SavClosureTriggerEnum(Enum):
	TIME = 0
	PRESSURE = 1

class AirValveTransitionType(Enum):
	BYVOLUME = 0
	BYPRESSURE = 1

class GasVesselLevelType(Enum):
	FIXED = 0
	MEAN = 1
	VARIABLE = 2

class HydroTankType(Enum):
	SEALED = 0
	VENTED = 1
	DIPPINGTUBE = 2

class AirFlowCalculationMethod(Enum):
	ORIFICEDIAMETER = 0
	AIRFLOWCURVE = 1

class PressureZoneScopeType(Enum):
	ENTIRENETWORK = 0
	NETWORKSUBSET = 1

class FlushingStatus(Enum):
	OPEN = 0
	CLOSED = 1
	TARGET = 2
	FLOWING = 3
	REOPEN = 4
	RECLOSE = 5
	OPENPRIOR = 6
	CLOSEDPRIOR = 7

class WaterSCADAField(Enum):
	NULLATTRIBUTE = 0
	OBSERVEDRELATIVECLOSURE = -300
	OBSERVEDCONSTITUENTCONCENTRATION = -299
	PRESSURENODEDEMAND = -297
	TANKINITIALHGLSETTING = -296
	TCVALVEINITIALSETTING = -208
	GPVALVEINITIALSETTING = -207
	VALVEINITIALSTATUS = -201
	PUMPINITIALSETTING = -200
	PUMPINITIALSTATUS = -199
	PRESSUREPIPEINITIALSTATUS = -198
	VSPTARGETHEAD = -191
	VSPCONTROLNODEID = -189
	OBSERVEDVALVESTATUS = -58
	OBSERVEDPUMPSTATUS = -57
	OBSERVEDPIPESTATUS = -56
	OBSERVEDTANKLEVEL = -55
	OBSERVEDPRESSURE = -54
	OBSERVEDHYDRAULICGRADE = -53
	OBSERVEDPUMPSETTING = -52
	OBSERVEDPRESSUREVALVESETTING = -51
	OBSERVEDTCVALVESETTING = -50
	OBSERVEDFCVALVESETTING = -49
	OBSERVEDPRESSUREOUT = -48
	OBSERVEDPRESSUREIN = -47
	OBSERVEDHYDRAULICGRADEOUT = -46
	OBSERVEDHYDRAULICGRADEIN = -45
	OBSERVEDDISCHARGE = -44
	TANKBASEELEVATION = -39
	DEMAND = -33
	INITIALHGLSETTING = -27
	FCVALVEINITIALSETTING = -26
	TANKACTIVEVOLUME = -10
	GROUNDELEVATION = -4

class PumpDefinitionTypeEnum(Enum):
	CONSTANTPOWERTYPE = 0
	DESIGNPOINTTYPE = 1
	STANDARDTYPE = 2
	STANDARDEXTENDEDTYPE = 3
	CUSTOMEXTENDEDTYPE = 4
	MULTIPLEPOINTTYPE = 5
	VOLUMEFLOW = 6
	DEPTHFLOW = 7
	DEPTHFLOWVARIABLESPEED = 8

class PumpEfficiencyTypeEnum(Enum):
	CONSTANTEFFICIENCYTYPE = 0
	BESTEFFICIENCYPOINTTYPE = 1
	MULTIPLEEFFICIENCYPOINTSTYPE = 2

class WallReactionOrderEnum(Enum):
	ZEROORDERTYPE = 0
	FIRSTORDERTYPE = 1

class ControlTypeEnum(Enum):
	LOGICALTYPE = 0
	SIMPLETYPE = 1

class ControlPriorityEnum(Enum):
	PRIORITYDEFAULTTYPE = 0
	PRIORITY1TYPE = 1
	PRIORITY2TYPE = 2
	PRIORITY3TYPE = 3
	PRIORITY4TYPE = 4
	PRIORITY5TYPE = 5

class ControlActionTypeEnum(Enum):
	SIMPLEACTIONTYPE = 0
	COMPOSITEACTIONTYPE = 1

class ElementTypeEnum(Enum):
	CONTROLACTIONFCVTYPE = 60
	CONTROLACTIONTCVTYPE = 61
	CONTROLACTIONGPVTYPE = 62
	CONTROLACTIONPRESSUREVALVETYPE = 63
	CONTROLACTIONPUMPTYPE = 68
	CONTROLACTIONPIPETYPE = 69

class PipeAttributeEnum(Enum):
	ACTIONPIPESTATUSTYPE = 0

class ActionPipeStatusEnum(Enum):
	OPENTYPE = 0
	OFFTYPE = 1

class PumpAttributeEnum(Enum):
	ACTIONPUMPSTATUSTYPE = 0
	ACTIONPUMPSETTINGTYPE = 1
	ACTIONPUMPPRESSURESETTING = 2
	ACTIONPUMPHEADSETTING = 3

class ActionPumpStatusEnum(Enum):
	ONTYPE = 0
	OFFTYPE = 1

class TCVAttributeEnum(Enum):
	ACTIONTCVSTATUSTYPE = 0
	ACTIONTCVSETTINGTYPE = 1

class TCVStatusEnum(Enum):
	CLOSEDTYPE = 0
	INACTIVETYPE = 1

class GPVAttributeEnum(Enum):
	ACTIONGPVSTATUSTYPE = 0

class GPVStatusEnum(Enum):
	CLOSEDTYPE = 0
	ACTIVETYPE = 1

class FCVAttributeEnum(Enum):
	ACTIONFCVSETTINGTYPE = 0
	ACTIONFCVSTATUSTYPE = 1

class FCVStatusEnum(Enum):
	CLOSEDTYPE = 0
	INACTIVETYPE = 1

class PRVAttributeEnum(Enum):
	ACTIONPRESSUREVALVESETTINGTYPE = 0
	ACTIONPRESSUREVALVESTATUSTYPE = 1
	ACTIONPRESSUREVALVESETTINGPRESSURE = 2

class ActionPressureValveStatusEnum(Enum):
	CLOSEDTYPE = 0
	INACTIVETYPE = 1

class ConditionTypeEnum(Enum):
	SIMPLECONDITIONTYPE = 0
	COMPOSITECONDITIONTYPE = 1

class SimpleConditionTypeEnum(Enum):
	ELEMENTTYPE = 0
	SYSTEMDEMANDTYPE = 1
	CLOCKTIMETYPE = 2
	TIMEFROMSTARTTYPE = 3

class ControlConditionPumpStatusEnum(Enum):
	ONTYPE = 0
	OFFTYPE = 1

class ControlConditionPipeStatusEnum(Enum):
	OPENTYPE = 0
	CLOSEDTYPE = 1

class ControlConditionGPVStatusEnum(Enum):
	CLOSEDTYPE = 0
	ACTIVETYPE = 1

class ControlConditionValveStatusEnum(Enum):
	CLOSEDTYPE = 0
	INACTIVETYPE = 1

class ControlConditionElementTypeEnum(Enum):
	CONTROLCONDITIONNODETYPE = 50
	CONTROLCONDITIONTANKTYPE = 52
	CONTROLCONDITIONFCVTYPE = 60
	CONTROLCONDITIONTCVTYPE = 61
	CONTROLCONDITIONGPVTYPE = 62
	CONTROLCONDITIONPRESSUREVALVETYPE = 63
	CONTROLCONDITIONPUMPTYPE = 68
	CONTROLCONDITIONPIPETYPE = 69
	CONTROLCONDITIONHYDROTANKTYPE = 302
	CONTROLCONDITIONSURGETANKTYPE = 308

class NodeAttributeEnum(Enum):
	NODEDEMANDTYPE = 0
	NODEHYDRAULICGRADETYPE = 1
	NODEPRESSURETYPE = 2

class TankAttributeEnum(Enum):
	TANKDEMANDTYPE = 0
	TANKHYDRAULICGRADETYPE = 1
	TANKPRESSURETYPE = 2
	TANKLEVELTYPE = 3
	TANKTIMETODRAINTYPE = 4
	TANKTIMETOFILLTYPE = 5
	TANKPERCENTFULLTYPE = 6

class HydroTankAttributeEnum(Enum):
	HYDROTANKHYDRAULICGRADETYPE = 1
	HYDROTANKPRESSURETYPE = 2

class SuctionDataTypeEnum(Enum):
	PRESSURE = 0
	LEVEL = 1

class DischargeDataTypeEnum(Enum):
	PRESSURE = 0
	LEVEL = 1

class SurgeTankAttributeEnum(Enum):
	SURGETANKDEMANDTYPE = 0
	SURGETANKHYDRAULICGRADETYPE = 1
	SURGETANKPRESSURETYPE = 2

class ControlConditionPumpAttributeEnum(Enum):
	PUMPDISCHARGETYPE = 0
	CONDITIONPUMPSETTINGTYPE = 1
	CONDITIONPUMPSTATUSTYPE = 2

class ConditionPipeAttributeEnum(Enum):
	PIPEDISCHARGETYPE = 0
	CONDITIONPIPESTATUSTYPE = 1

class ControlConditionPressureValveAttributeEnum(Enum):
	PRESSUREVALVEDISCHARGETYPE = 0
	PRESSUREVALVESETTINGTYPE = 1
	PRESSUREVALVESTATUSTYPE = 2

class ControlConditionFCVAttributeEnum(Enum):
	FCVDISCHARGETYPE = 0
	FCVSETTINGTYPE = 1
	FCVSTATUSTYPE = 2

class ControlConditionGPVAttributeEnum(Enum):
	GPVDISCHARGETYPE = 0
	GPVSTATUSTYPE = 1

class ControlConditionTCVAttributeEnum(Enum):
	TCVDISCHARGETYPE = 0
	TCVSETTINGTYPE = 1
	TCVSTATUSTYPE = 2

class CompareOperatorEnum(Enum):
	EQUALSTYPE = 0
	GREATERTHANTYPE = 1
	GREATERTHANEQUALTYPE = 2
	LESSTHANTYPE = 3
	LESSTHANEQUALTYPE = 4
	NOTEQUALTYPE = 5

class LogicalOperatorEnum(Enum):
	OPERATORIFTYPE = 0
	OPERATORANDTYPE = 1
	OPERATORORTYPE = 2

class UnitDemandLoadTypeEnum(Enum):
	POPULATIONBASEDTYPE = 0
	AREABASEDTYPE = 1
	COUNTUNITTYPE = 3

class EquivalentPipeMethodEnum(Enum):
	MODIFYDIAMETERTYPE = 0
	MODIFITYROUGHNESSTYPE = 1

class DominantPipeCriteriaEnum(Enum):
	DOMBULKREACTIONRATETYPE = 0
	DOMDIAMETERTYPE = 1
	DOMINSTALLATIONYEARTYPE = 2
	DOMLENGTHTYPE = 3
	DOMMINORLOSSCOEFFICIENTTYPE = 4
	DOMROUGHNESSTYPE = 5
	DOMWALLREACTIONRATETYPE = 6

class SkelebratorTypeEnum(Enum):
	SMARTPIPEREMOVALTYPE = 0
	BRANCHCOLLAPSINGTYPE = 1
	SERIESPIPEMERGINGTYPE = 2
	PARALLELPIPEMERGINGTYPE = 3
	INLINEISOLATINGVALVEREPLACEMENTTYPE = 4

class BranchLoadDistributionStrategyEnum(Enum):
	MOVELOADTYPE = 0
	DONTMOVELOADTYPE = 1

class SeriesLoadDistributionStrategyEnum(Enum):
	EQUALLYDISTRIBUTEDTYPE = 0
	PROPORTIONALTODOMINANTCRITERIATYPE = 1
	PROPORTIONALTOEXISTINGLOADTYPE = 2
	USERDEFINEDRATIOTYPE = 3

class MinorLossStrategyEnum(Enum):
	FIFTYFIFTYSPLITYTYPE = 0
	IGNOREMINORLOSSESTYPE = 1
	SKIPPIPEMINORLOSSGREATERTHANMAXTYPE = 2

class MaterialConditionEnum(Enum):
	CONDITIONSAMETYPE = 0
	CONDITIONDIFFERENTTYPE = 1

class PipeConditionAttributeTypeEnum(Enum):
	CONDITIONBULKREACTIONRATETYPE = 0
	CONDITIONDIAMETERTYPE = 1
	CONDITIONHASCHECKVALVETYPE = 2
	CONDITIONINSTALLATIONYEARTYPE = 3
	CONDITIONLENGTHTYPE = 4
	CONDITIONMATERIALTYPE = 5
	CONDITIONMINORLOSSCOEFFICIENTTYPE = 6
	CONDITIONROUGHNESSTYPE = 7
	CONDITIONWALLREACTIONRATETYPE = 8
	CONDITIONWAVESPEED = 9

class PipeConditionOperatorTypeEnum(Enum):
	PIPECONDITIONLESSTHANTYPE = 0
	PIPECONDITIONGREATERTHANTYPE = 1
	PIPECONDITIONLESSTHANEQUALTYPE = 2
	PIPECONDITIONGREATERTHANEQUALTYPE = 3
	PIPECONDITIONEQUALTYPE = 4
	PIPECONDITIONNOTEQUALTYPE = 5
	PIPECONDITIONTOLERANCETYPE = 6

class JunctionConditionAttributeTypeEnum(Enum):
	CONDITIONBASEFLOWTYPE = 0
	CONDITIONELEVATIONTYPE = 1
	CONDITIONEMITTERCOEFFICIENTTYPE = 2

class JunctionConditionOperatorEnum(Enum):
	JUNCTIONCONDITIONLESSTHANTYPE = 0
	JUNCTIONCONDITIONGREATERTHANTYPE = 1
	JUNCTIONCONDITIONLESSTHANEQUALTYPE = 2
	JUNCTIONCONDITIONGREATERTHANEQUALTYPE = 3
	JUNCTIONCONDITIONEQUALTYPE = 4
	JUNCTIONCONDITIONNOTEQUALTYPE = 5
	JUNCTIONCONDITIONTOLERANCETYPE = 6

class IdahoSupportElementTypes(Enum):
	IDAHOPATTERNELEMENTMANAGER = 50
	IDAHOPUMPDEFINITIONELEMENTMANAGER = 51
	IDAHOCONSTITUENTELEMENTMANAGER = 52
	ZONEELEMENTMANAGER = 53
	IDAHOCONTROLELEMENTMANAGER = 54
	IDAHOCONTROLACTIONELEMENTMANAGER = 55
	IDAHOCONTROLCONDITIONELEMENTMANAGER = 56
	IDAHOLOGICALCONTROLSETELEMENTMANAGER = 59
	PRESSUREDEPENDENTDEMANDFUNCTIONELEMENTMANAGER = 60
	ENERGYPRICINGELEMENTMANAGER = 61
	UNITDEMANDLOADELEMENTMANAGER = 62
	GPVHEADLOSSCURVEELEMENTMANAGER = 63

