from enum import Enum
from System import TypeCode

class TargetAttribute(Enum):
	NULLATTRIBUTE = 0
	SS_DEPTH = 1
	SS_DEPTHIN = 2
	SS_DEPTHOUT = 3
	SS_VELOCITYIN = 4
	SS_VELOCITYOUT = 5
	TANKSTATUS = -301
	RELATIVECLOSURE = -300
	CONSTITUENTCONCENTRATION = -299
	PRESSURENODEDEMAND = -297
	VALVESTATUS = -58
	PUMPSTATUS = -57
	PIPESTATUS = -56
	TANKLEVEL = -55
	PRESSURE = -54
	HYDRAULICGRADE = -53
	PUMPSETTING = -52
	PRESSUREVALVESETTING = -51
	TCVALVESETTING = -50
	FCVALVESETTING = -49
	PRESSUREOUT = -48
	PRESSUREIN = -47
	HYDRAULICGRADEOUT = -46
	HYDRAULICGRADEIN = -45
	DISCHARGE = -44
	WIREPOWER = -43
	SS_SURFACEELEVATION = -7

class ActiveAlarmsEnum(Enum):
	NONE = 0
	LOW = 1
	HIGH = 2
	LOWHIGH = 3
	ALL = 4

